---
title: "Untitled"
output:
  md_document: null
  pdf_document:
    fig_height: 3
    fig_width: 4.5
---

```{r, setup, include=FALSE}
library(tidyverse)
library(stringr)
library(rvest)
library(httr)
```

## Web Scraping Ideas

```{r}
opiateuse <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_prevalence_of_opiates_use")
opiateuse2 <- html_nodes(opiateuse, css = "table")
opiateusetable <- as.tibble(html_table(opiateuse2, header = TRUE, fill = TRUE)[[1]])
opiateusetable

cannabisuse <- read_html("https://en.wikipedia.org/wiki/Annual_cannabis_use_by_country")
cannabisuse2 <- html_nodes(cannabisuse, css = "table")
cannabisusetable <- as.tibble(html_table(cannabisuse2, header = TRUE, fill = TRUE)[[1]])
cannabisusetable

cocaineuse <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_prevalence_of_cocaine_use")
cocaineuse2 <- html_nodes(cocaineuse, css = "table")
cocaineusetable <- as.tibble(html_table(cocaineuse2, header = TRUE, fill = TRUE)[[1]])
cocaineusetable

governmentsystem <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_system_of_government")
governmentsystem2 <- html_nodes(governmentsystem, css = "table")
governmentsystemtable <- as.tibble(html_table(governmentsystem2, header = TRUE, fill = TRUE)[[6]])
governmentsystemtable

governmentbudget <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_government_budget")
governmentbudget2 <- html_nodes(governmentbudget, css = "table")
governmentbudgettable <- as.tibble(html_table(governmentbudget2, header = TRUE, fill = TRUE)[[1]])
governmentbudgettable

gdppercapita <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)_per_capita")
gdppercapita2 <- html_nodes(gdppercapita, css = "table")
gdppercapitatable <- as.tibble(html_table(gdppercapita2, header = TRUE, fill = TRUE)[[5]])
gdppercapitatable

pop <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)")
pop2 <- html_nodes(pop, css = "table")
poptable <- as.tibble(html_table(pop2, header = TRUE, fill = TRUE)[[3]])
poptable

# gdp <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)")
# gdp2 <- html_nodes(gdp, css = "table")
# gdptable <- html_table(gdp2, header = TRUE, fill = TRUE)[[5]]
# gdptable

# intentionalhomocide <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_intentional_homicide_rate")
# intentionalhomocide2 <- html_nodes(intentionalhomocide, css = "table")
# intentionalhomocidetable <- html_table(intentionalhomocide2, header = TRUE, fill = TRUE)[[3]]
# intentionalhomocidetable

# prisonrate <- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_incarceration_rate")
# prisonrate2 <- html_nodes(prisonrate, css = "table")
# prisonratetable <- html_table(prisonrate2, header = FALSE, fill = TRUE)[[1]]
# prisonratetable
```

```{r}
mastertable <- gdppercapitatable%>%
  left_join(governmentbudgettable, by = "Country")%>%
  select("Country", "US$", "Revenues", "Expenditures", "Surplus (or deficit)", "Year")%>%
  left_join(governmentsystemtable, by = c("Country" = "Name"))%>%
  left_join(opiateusetable, by = c("Country" = "Country or Entity"))%>%
  left_join(cannabisusetable, by = c("Country" = "Country or entity"))%>%
  left_join(cocaineusetable, by = c("Country" = "Country or entity"))%>%
  select("Country", "Year.x", "US$", "Revenues", "Expenditures", "Surplus (or deficit)", "Constitutional form", "Head of state", "Annual prevalence (percent).x", "Annual prevalence\n(percent)","Annual prevalence (percent).y")%>%
  rename("Revenues(millions)" = "Revenues", "GDP per Capita" = "US$", "Expenditures(millions)" = "Expenditures", "Surplus/Deficit(millions)" = "Surplus (or deficit)","Year" = "Year.x", "Opiate Prevalence(percent)" = "Annual prevalence (percent).x", "Cannabis Prevalence(percent)" = "Annual prevalence\n(percent)", "Cocaine Prevalence(percent)" = "Annual prevalence (percent).y")

mastertable
```
